---
- hosts: localhost 
  name: Add hosts to dvSwitch
  gather_facts: false
  tasks:
  - community.vmware.vmware_dvs_host:
      hostname: '192.168.1.199'
      username: 'administrator@vsphere.local'
      password: 'VMware1!'
      esxi_hostname: '192.168.1.53'
      switch_name: dvSwitch
      vmnics:
              - vmnic1
      state: present
      validate_certs: no
    delegate_to: localhost


