---
- hosts: localhost 
  name: add vmotin vmk to vds
  gather_facts: false
  tasks:
  - community.vmware.vmware_vmkernel:
      hostname: '192.168.1.199'
      username: 'administrator@vsphere.local'
      password: 'VMware1!'
      esxi_hostname: '192.168.1.51'
      dvswitch_name: dvSwitch
      portgroup_name: vmotion_vmk1
      network:
              type: 'static'
              ip_address: 192.168.1.151
              subnet_mask: 255.255.255.0
              tcpip_stack: vmotion
      state: present
      validate_certs: no
    delegate_to: localhost

  - community.vmware.vmware_vmkernel:
      hostname: '192.168.1.199'
      username: 'administrator@vsphere.local'
      password: 'VMware1!'
      esxi_hostname: '192.168.1.52'
      dvswitch_name: dvSwitch
      portgroup_name: vmotion_vmk1
      network:
              type: 'static'
              ip_address: 192.168.1.152
              subnet_mask: 255.255.255.0
              tcpip_stack: vmotion
      state: present
      validate_certs: no
    delegate_to: localhost
  - community.vmware.vmware_vmkernel:
      hostname: '192.168.1.199'
      username: 'administrator@vsphere.local'
      password: 'VMware1!'
      esxi_hostname: '192.168.1.53'
      dvswitch_name: dvSwitch
      portgroup_name: vmotion_vmk1
      network:
              type: 'static'
              ip_address: 192.168.1.153
              subnet_mask: 255.255.255.0
              tcpip_stack: vmotion
      state: present
      validate_certs: no
    delegate_to: localhost



